Update README for AlmaLinux
AlmaLinux/leapp-repository pull request #106
Opened 2024-04-10 10:13 UTC by prilr

2024-08-07 04:16 UTC, shakaran commented
@prilr could you rebase again the conflicts? Thanks

2024-08-07 13:32 UTC, prilr commented
@shakaran Done.

2024-08-07 17:03 UTC, shakaran commented
@pirat89 @codyro @andrewlukoshko @bennyvasquez could you merge this? Thanks

2024-08-22 14:53 UTC, andrewlukoshko requested changes

2024-08-22 14:53 UTC, andrewlukoshko commented on README.md
> +`sudo yum install -y http://repo.almalinux.org/elevate/elevate-release-latest-el7.noarch.rpm`
Replace with:
```
sudo yum install -y http://repo.almalinux.org/elevate/elevate-release-latest-el$(rpm --eval %rhel).noarch.rpm
```

2024-08-22 14:59 UTC, prilr commented on README.md
> +`sudo yum install -y http://repo.almalinux.org/elevate/elevate-release-latest-el7.noarch.rpm`
Done.

2024-08-22 15:00 UTC, merged