Modify efibootorderfix to support distro changes
AlmaLinux/leapp-repository pull request #3
Opened 2022-04-15 16:40 UTC by guzzijason

AlmaLinux/leapp-repository supports upgrades to different OS
distributions (e.g. CentOS 7 -> Rocky 8); however the
efibootorderfix (finalization) actor only assumes you are
upgrading to the same distro (e.g. Redhat 7 -> Redhat 8). This
causes first boot to fail on UEFI-enabled hardware post-upgrade.
This patch makes the EFI bootloader entry configuration more flexible
to support distro changes.

The two main functions of this patch:

1. Ensure that the EFI bootloader path is correct for the OS distribution we are upgrading to, and
2. Check to see if a `grub.cfg` exists in the new EFI path, and if not, generate one

2022-04-15 17:34 UTC, guzzijason commented
Here is an example of the efibootmgr config before and after a successful upgrade from CentOS 7 -> Rocky 8 using this patch:

**Before Upgrade:**
```
[root@r7415-01 ~]# cat /etc/system-release
CentOS Linux release 7.9.2009 (Core)
[root@r7415-01 ~]# efibootmgr -v
BootCurrent: 0002
BootOrder: 0002,0003,0001,0004
Boot0001* Virtual Floppy	/Pci(0x7,0x1)/Pci(0x0,0x3)/USB(0,0)/USB(0,0)/USB(2,0)/Unit(1)
Boot0002* CentOS	HD(1,GPT,7f3b4e34-5f01-4747-bacb-06b87298f4c7,0x800,0x64000)/File(\EFI\centos\shimx64.efi)
Boot0003  Embedded NIC 1 Port 1 Partition 1	VenHw(3a191845-5f86-4e78-8fce-c4cff59f9daa)
Boot0004* Virtual CD	/Pci(0x7,0x1)/Pci(0x0,0x3)/USB(0,0)/USB(0,0)/USB(2,0)/Unit(0)
```

**After Upgrade:**
```
[root@r7415-01 ~]# cat /etc/system-release
Rocky Linux release 8.5 (Green Obsidian)
[root@r7415-01 ~]# efibootmgr -v
BootCurrent: 0000
BootOrder: 0000,0002,0003,0001,0004
Boot0000* Rocky Linux 8	HD(1,GPT,7f3b4e34-5f01-4747-bacb-06b87298f4c7,0x800,0x64000)/File(\EFI\rocky\shimx64.efi)
Boot0001* Virtual Floppy	PciRoot(0x1)/Pci(0x7,0x1)/Pci(0x0,0x3)/USB(0,0)/USB(0,0)/USB(2,0)/Unit(1)
Boot0002* CentOS	HD(1,GPT,7f3b4e34-5f01-4747-bacb-06b87298f4c7,0x800,0x64000)/File(\EFI\centos\shimx64.efi)
Boot0003  Embedded NIC 1 Port 1 Partition 1	VenHw(3a191845-5f86-4e78-8fce-c4cff59f9daa)
Boot0004* Virtual CD	PciRoot(0x1)/Pci(0x7,0x1)/Pci(0x0,0x3)/USB(0,0)/USB(0,0)/USB(2,0)/Unit(0)
```

2022-05-29 18:20 UTC, evgeni commented on repos/system_upgrade/common/actors/efibootorderfix/finalization/actor.py
> +                                distro = line.split(' release ',1)[0]
you should be able to use `self.configuration.os_release.release_id` instead.

with the following values, `rhel`, `centos`, `rocky`, `ol`, `almalinux`

2022-06-14 19:36 UTC, guzzijason commented on repos/system_upgrade/common/actors/efibootorderfix/finalization/actor.py
> +                                distro = line.split(' release ',1)[0]
@evgeni thanks for the tip; I'll have an updated commit shortly.

2022-06-14 21:22 UTC, guzzijason commented
Actually, after the revision, I'm not having problems with testing. I'm not sure yet, but I suspect that `self.configuration.os_release.release_id` may be returning the original OS release ("centos") and not the upgraded release ("rocky"). The upgraded system fails to boot. Will need to debug further.

2022-06-14 21:49 UTC, evgeni commented
Oh yeah, it will be the release at the beginning of the leapp run, not of the result.

2022-06-14 22:23 UTC, guzzijason commented
I've reverted back to the original method for now. I'm open to suggestions, however, if anyone does know of a cleaner solution.

2022-06-22 20:38 UTC, ylluminate commented
Similar, but not the same should also be considered this (scenario was with Linode (that does not use EFI)): https://github.com/cpanel/elevate/issues/101

2022-09-29 00:06 UTC, andrewlukoshko commented on repos/system_upgrade/common/actors/efibootorderfix/finalization/actor.py
> +                                distro = line.split(' release ',1)[0]
@guzzijason any updates?

2022-09-29 00:13 UTC, andrewlukoshko commented
@guzzijason could you please also add ARM64 support?
It uses shimaa64.efi as shim filename

2022-09-29 00:18 UTC, andrewlukoshko commented on repos/system_upgrade/common/actors/efibootorderfix/finalization/actor.py
> +        release = distro + " 8"
We're working on EL9 support so I think we should get version from /etc/system-release too

2022-09-29 00:20 UTC, andrewlukoshko requested changes

2022-09-29 00:20 UTC, andrewlukoshko commented on repos/system_upgrade/common/actors/efibootorderfix/finalization/actor.py
> +        release = distro + " 8"
We're working on EL9 support so I think we should get version from /etc/system-release too

2022-09-29 00:20 UTC, andrewlukoshko commented on repos/system_upgrade/common/actors/efibootorderfix/finalization/actor.py
> +        shim_path = '/boot/efi/EFI/' + distro_dir + '/shimx64.efi'
aarch64 systems use shimaa64.efi as filename
arch detection logic is needed here

2022-09-29 04:50 UTC, prilr commented on repos/system_upgrade/common/actors/efibootorderfix/finalization/actor.py
> +        has_efibootmgr = os.path.exists('/sbin/efibootmgr')
Does `has_efibootmgr` serve any purpose at the moment?

2022-09-29 04:50 UTC, prilr commented on repos/system_upgrade/common/actors/efibootorderfix/finalization/actor.py
> +                                distro = line.split(' release ',1)[0]
Seems like Leapp doesn't have a simple way to retrieve the name of the target distro at the moment.
In fact, I don't think it's aware of what the target distro is at all, only the target system version.
As things stand, looks like this is the most expedient option.

2022-09-29 04:50 UTC, prilr commented on repos/system_upgrade/common/actors/efibootorderfix/finalization/actor.py
> -from leapp.libraries.common import efi_reboot_fix
Does this mean that `leapp-repository/repos/system_upgrade/common/libraries/efi_reboot_fix.py` is no longer needed?

2022-09-30 20:49 UTC, guzzijason commented on repos/system_upgrade/common/actors/efibootorderfix/finalization/actor.py
> -from leapp.libraries.common import efi_reboot_fix
Yes, seems unnecessary from what I can see.

2022-09-30 20:58 UTC, guzzijason commented on repos/system_upgrade/common/actors/efibootorderfix/finalization/actor.py
> +        has_efibootmgr = os.path.exists('/sbin/efibootmgr')
I think that perhaps my thinking at the time was to incorporate something like the following - basically do a noop if this isn't an EFI machine - I'm not sure if this is strictly necessary, though:

https://github.com/AlmaLinux/leapp-repository/blob/master/repos/system_upgrade/common/libraries/efi_reboot_fix.py#L27-L34

2022-09-30 20:59 UTC, guzzijason commented
@prilr those commits look reasonable to me

2022-10-03 17:46 UTC, guzzijason commented on repos/system_upgrade/common/actors/efibootorderfix/finalization/actor.py
> +        has_efibootmgr = os.path.exists('/sbin/efibootmgr')
I've added that logic to latest commit (#[370409f](https://github.com/AlmaLinux/leapp-repository/pull/3/commits/370409f5d4ff4bb2c254ded37a0b6f4f11be2e5b)

2022-10-03 17:47 UTC, guzzijason commented
Tested  OK in my environment using both UEFI and legacy BIOS hosts (CentOS 7 -> Rocky 8)

2022-10-03 18:20 UTC, merged